### ISSUE TITLE
require active_support dependencies

### ISSUE THREAD

**Issue by stooj** [jugyo/earthquake#169]
Not familiar with ruby, so apologies if I am missing out important info.

Installed earthquake 1.0.1 using gem install earthquake, but it crashed when I tried to launch it with the following:

```
/home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>': uninitialized constant ActiveSupport::Autoload (NameError)
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/number_helper.rb:1:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in `each'
from /home/user/.gem/ruby/2.1.0/gems/activesupport-4.1.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/user/.gem/ruby/2.1.0/gems/earthquake-1.0.1/lib/earthquake.rb:16:in `block in <top (required)>'
from /home/user/.gem/ruby/2.1.0/gems/earthquake-1.0.1/lib/earthquake.rb:16:in `each'
from /home/user/.gem/ruby/2.1.0/gems/earthquake-1.0.1/lib/earthquake.rb:16:in `<top (required)>'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
from /home/user/.gem/ruby/2.1.0/gems/earthquake-1.0.1/bin/earthquake:36:in `<top (required)>'
from /home/user/.gem/ruby/2.1.0/bin/earthquake:23:in `load'
from /home/user/.gem/ruby/2.1.0/bin/earthquake:23:in `<main>'
```

I found similar issues and the problem seems to be using some deprecated
features from active_support (see http://omf.mytestbed.net/issues/1726 )

I added 

``` ruby
require 'active_support'
require 'active_support/deprecation'
```

to the top of earthquake-1.0.1/bin/earthquake and it launches fine now.

**Comment by cirrusUK** [comment]
Thanks i had same issues with ruby 2.2.0 and earthquake 1.0.2 this worked for me too, only i get this at launch /home/cirrus/.gem/ruby/2.2.0/gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb:27: warning: duplicated key at line 30 ignored: :path 
still earthquake launches fine.
