### ISSUE TITLE
OSX mavericks 'function is unimplemented'

### ISSUE THREAD

**Issue by cirrusUK** [jugyo/earthquake#176]
Hi
 I've been tryin to install my fave twitter client on osx mavericks, heres what i get ..  after rvm openssl,readline & gem install earthquake
```
 / _ \/ _` | '__| __| '_ \ / _` | | | |/ _` | |/ / _ \
|  __/ (_| | |  | |_| | | | (_| | |_| | (_| |   <  __/
 \___|\__,_|_|   \__|_| |_|\__, |\__,_|\__,_|_|\_\___|
                              |_|               v1.0.2

[$ab] NorwichCityFC: RT @stephenfry: Whoop! My @NorwichCityFC @ProstateUK logo is here. Join #MenUnited http://t.co/RAN6KLxPQT Prost8, see! #NCFC http://t.co/en53G8IKGb (retweet of $aa) - 09 Oct 18:03 - TweetDeck
/Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/output.rb:64:in `refresh_line': refresh_line() function is unimplemented on this machine (NotImplementedError)
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/output.rb:64:in `block in insert'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/monitor.rb:211:in `mon_synchronize'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/output.rb:54:in `insert'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/output.rb:24:in `output'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:151:in `block (3 levels) in start'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:234:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:234:in `block in sync'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:233:in `synchronize'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:233:in `sync'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:151:in `block (2 levels) in start'
        from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/em/timers.rb:56:in `fire'
        from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `call'
        from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
        from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/lib/earthquake/core.rb:130:in `start'
        from /Library/Ruby/Gems/2.0.0/gems/earthquake-1.0.2/bin/earthquake:39:in `<top (required)>'
        from /usr/bin/earthquake:23:in `load'
        from /usr/bin/earthquake:23:in `<main>'
```

**Comment by haikieu** [comment]
I get same issues like this , please fix. 
I'm using MAC OS

**Comment by mattn** [comment]
refresh_line is implemented on ruby19. you still using ruby19?

**Comment by haikieu** [comment]
I'm tried to install the readling from terminal by command:
sudo port install readline
but still get back the issue.


@mattn how to check & install ruby19 ?

**Comment by cirrusUK** [comment]
I got working on mavericks using ruby 2.0.0 after following steps https://github.com/jugyo/earthquake/issues/169 by adding the 2 lines to the top of /bin/earthquake  and commenting out line 30 of gems/twitter-stream-0.1.16/lib/twitter/json_stream.rb  hope this helps
